name: Push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
on:
  merge_group:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install DNSControl
        uses: gacts/install-dnscontrol@v1
        #with:
        #  version: 3.20.0 # `latest` by default, but you can set a specific version to install

      - name: Connect to Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:github-runner

      - name: DNSControl push
        id: dnscontrol_push
        run: ./ci.sh push
        env:
          CLOUDFLARE_ACCOUNTID: ${{ secrets.CLOUDFLARE_ACCOUNTID }}
          CLOUDFLARE_APITOKEN: ${{ secrets.CLOUDFLARE_APITOKEN }}
          TSIG_CI: ${{ secrets.TSIG_CI }}

#      - name: Create or update comment
#        uses: peter-evans/create-or-update-comment@v3
#        with:
#          issue-number: ${{ github.event.pull_request.number }}
#          body: |
#              ```
#              push output:
#              ${{ steps.dnscontrol_push.outputs.push_comment }}
#              ```
#          edit-mode: replace
