name: Push

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install DNSControl
        uses: gacts/install-dnscontrol@v1
        #with:
        #  version: 3.20.0 # `latest` by default, but you can set a specific version to install

      - name: DNSControl push
        run: dnscontrol push # any dnscontrol command can be executed
        #uses: koenrh/dnscontrol-action@v3
        env:
          CLOUDFLARE_ACCOUNTID: ${{ secrets.CLOUDFLARE_ACCOUNTID }}
          CLOUDFLARE_APITOKEN: ${{ secrets.CLOUDFLARE_APITOKEN }}
